meta: update recipes R36.3.0/JetPack 6 -> R36.4.0/JetPack 6.1
Signed-off-by: Ilies CHERGUI <ichergui@nvidia.com>
Signed-off-by: Matt Madison <matt@madison.systems>

diff --git a/recipes-bsp/tegra-binaries/files/0010-Rework-logging-in-l4t_sign_image.sh.patch b/recipes-bsp/tegra-binaries/files/0010-Rework-logging-in-l4t_sign_image.sh.patch
--- a/recipes-bsp/tegra-binaries/files/0010-Rework-logging-in-l4t_sign_image.sh.patch
+++ b/recipes-bsp/tegra-binaries/files/0010-Rework-logging-in-l4t_sign_image.sh.patch
@@ -1,6 +1,6 @@
-From d0aa71084a824059808d45804211b1fbf2f0d152 Mon Sep 17 00:00:00 2001
+From ae17e4099d84b9facc61bba187fb3ed32c37cccf Mon Sep 17 00:00:00 2001
 From: Ilies CHERGUI <ichergui@nvidia.com>
-Date: Wed, 28 Feb 2024 19:55:34 +0000
+Date: Sun, 6 Oct 2024 15:20:59 +0100
 Subject: [PATCH] Rework logging in l4t_sign_image.sh
 
 to be more compatible with the pseudo environment during
@@ -10,35 +10,52 @@ cloning that the script was using.
 Upstream-Status: Inappropriate [OE specific]
 
 Signed-off-by: Matt Madison <matt@madison.systems>
+Signed-off-by: Ilies CHERGUI <ichergui@nvidia.com>
 ---
- l4t_sign_image.sh | 22 ++++++++--------------
- 1 file changed, 8 insertions(+), 14 deletions(-)
+ l4t_sign_image.sh | 20 +++++++-------------
+ 1 file changed, 7 insertions(+), 13 deletions(-)
 
 diff --git a/l4t_sign_image.sh b/l4t_sign_image.sh
-index e75bac1..085f50f 100755
+index cff2872..f4cb962 100755
 --- a/l4t_sign_image.sh
 +++ b/l4t_sign_image.sh
-@@ -91,7 +91,7 @@ function write_size_to_sig
- 	local sig_file="${1}"
- 	local size="${2}"
- 	if [ "${chip}" != "0x19" ]; then
--		echo "${SCRIPT_NAME}: chip ${chip}: Don't need to do anything" >&5
-+		[ $quiet -eq 1 ] || echo "${SCRIPT_NAME}: chip ${chip}: Don't need to do anything"
- 		return 0
- 	fi
- 	local offset=${FILE_SIZE_OFFSET_T19x}
-@@ -107,8 +107,8 @@ function write_size_to_sig
+@@ -112,8 +112,8 @@ function write_size_to_sig
  	fi
  	local tempfile
  	tempfile=$(mktemp)
 -	echo "${SCRIPT_NAME}: chip ${chip}: add $(printf "0x%x" "${size}") to offset "\
 -		"$(printf "0x%x" "${offset}") in sig file" >&5
 +	[ $quiet -eq 1 ] || echo "${SCRIPT_NAME}: chip ${chip}: add $(printf "0x%x" "${size}") to offset "\
-+               "$(printf "0x%x" "${offset}") in sig file"
++                "$(printf "0x%x" "${offset}") in sig file"
  	# Convert size to bytes in little endian
  	python3 -c "f = open(\"${tempfile}\",'wb'); f.write(int(${size}).to_bytes(8,'little')); f.close()"
  	# write to header at position 0x8
-@@ -240,13 +240,6 @@ elif [ "${enable_user_kdk}" != "False" ]; then
+@@ -138,8 +138,9 @@ function set_params_using_chipid
+ function sign_file
+ {
+ 	local sig_file="${1}"
+-	echo "${CMD} --chip ${chip} ${options[*]} --cmd sign ${sig_file} ${ftype}" >&5
+-	output="$("${CMD}" --chip "${chip}" "${options[@]}" --cmd "sign \"${sig_file}\" \"${ftype}\"" | tee >(cat - >&5))"
++	[ $quiet -eq 1 ] || "${CMD} --chip ${chip} ${options[*]} --cmd sign ${file} ${ftype}"
++	output="$("${CMD}" --chip "${chip}" "${options[@]}" --cmd "sign \"${file}\" \"${ftype}\"")"
++	[ $quiet -eq 1 ] || echo $output
+ 	if [ -n "${encryptkey}" ]; then
+ 		signedfile="$(echo "${output}" | grep "Signed and encrypted file:" | \
+ 		sed -n "s/.*Signed and encrypted file: //p")"
+@@ -150,10 +151,10 @@ function sign_file
+ 		echo "${SCRIPT_NAME}: Error: Unable to find the signed file generated by tegraflash.py" >&2
+ 		exit 6;
+ 	fi
+-	echo "${SCRIPT_NAME}: Generate header for $(basename "${signedfile}")" >&5
++	[ $quiet -eq 1 ] || echo "${SCRIPT_NAME}: Generate header for $(basename "${signedfile}")"
+ 	dd if="${signedfile}" of="${sig_file}.sig" bs="${offset}" count=1 > /dev/null 2>&1;
+ 	write_size_to_sig "${sig_file}.sig" "${file_size}"
+-	echo "${SCRIPT_NAME}: Generate 16-byte-size-aligned base file for $(basename "${signedfile}")" >&5
++	[ $quiet -eq 1 ] || echo "${SCRIPT_NAME}: Generate 16-byte-size-aligned base file for $(basename "${signedfile}")"
+ 	dd if="${signedfile}" of="${sig_file}" bs="${offset}" skip="1" > /dev/null 2>&1;
+ 	if [[ "${signedfile}" = *_sigheader.encrypt.signed ]]; then
+ 		filename=$(basename -- "$file")
+@@ -310,13 +311,6 @@ elif [ "${enable_user_kdk}" != "False" ]; then
  	exit 1
  fi
  
@@ -52,28 +69,6 @@ index e75bac1..085f50f 100755
  set_params_using_chipid
  
  CMD="${L4T_BOOTLOADER_DIR}/tegraflash.py"
-@@ -261,8 +254,9 @@ if [ "${enable_user_kdk}" == "True" ]; then
- 	options+=("--enable_user_kdk")
- fi
- 
--echo "${CMD} --chip ${chip} ${options[*]} --cmd sign ${file} ${ftype}" >&5
--output="$("${CMD}" --chip "${chip}" "${options[@]}" --cmd "sign \"${file}\" \"${ftype}\"" | tee >(cat - >&5))"
-+[ $quiet -eq 1 ] || "${CMD} --chip ${chip} ${options[*]} --cmd sign ${file} ${ftype}"
-+output="$("${CMD}" --chip "${chip}" "${options[@]}" --cmd "sign \"${file}\" \"${ftype}\"")"
-+[ $quiet -eq 1 ] || echo $output
- if [ -n "${encryptkey}" ]; then
- 	signedfile="$(echo "${output}" | grep "Signed and encrypted file:" | \
- 	sed -n "s/.*Signed and encrypted file: //p")"
-@@ -273,10 +267,10 @@ if ! [ -f "${signedfile}" ]; then
- 	echo "${SCRIPT_NAME}: Error: Unable to find the signed file generated by tegraflash.py" >&2
- 	exit 6;
- fi
--echo "${SCRIPT_NAME}: Generate header for $(basename "${signedfile}")" >&5
-+[ $quiet -eq 1 ] || echo "${SCRIPT_NAME}: Generate header for $(basename "${signedfile}")"
- dd if="${signedfile}" of="${file}.sig" bs="${offset}" count=1 > /dev/null 2>&1;
- write_size_to_sig "${file}.sig" "${file_size}"
--echo "${SCRIPT_NAME}: Generate 16-byte-size-aligned base file for $(basename "${signedfile}")" >&5
-+[ $quiet -eq 1 ] || echo "${SCRIPT_NAME}: Generate 16-byte-size-aligned base file for $(basename "${signedfile}")"
- dd if="${signedfile}" of="${file}" bs="${offset}" skip="1" > /dev/null 2>&1;
- if [[ "${signedfile}" = *_sigheader.encrypt.signed ]]; then
- 	filename=$(basename -- "$file")
+-- 
+2.34.1
+
