tegra-binaries, tegra-sources: update for L4T R32.7.1
Signed-off-by: Matt Madison <matt@madison.systems>

diff --git a/recipes-bsp/tegra-binaries/files/0010-Rework-logging-in-l4t_sign_image.sh.patch b/recipes-bsp/tegra-binaries/files/0010-Rework-logging-in-l4t_sign_image.sh.patch
--- a/recipes-bsp/tegra-binaries/files/0010-Rework-logging-in-l4t_sign_image.sh.patch
+++ b/recipes-bsp/tegra-binaries/files/0010-Rework-logging-in-l4t_sign_image.sh.patch
@@ -16,7 +16,7 @@ Index: Linux_for_Tegra/l4t_sign_image.sh
 ===================================================================
 --- Linux_for_Tegra.orig/l4t_sign_image.sh
 +++ Linux_for_Tegra/l4t_sign_image.sh
-@@ -77,7 +77,7 @@ function write_size_to_sig
+@@ -85,7 +85,7 @@ function write_size_to_sig
  	local sig_file="${1}"
  	local size="${2}"
  	if [ "${chip}" != "0x19" ]; then
@@ -25,7 +25,7 @@ Index: Linux_for_Tegra/l4t_sign_image.sh
  		return 0
  	fi
  	local offset=${FILE_SIZE_OFFSET_T19x}
-@@ -93,8 +93,8 @@ function write_size_to_sig
+@@ -101,8 +101,8 @@ function write_size_to_sig
  	fi
  	local tempfile
  	tempfile=$(mktemp)
@@ -36,7 +36,7 @@ Index: Linux_for_Tegra/l4t_sign_image.sh
  	# Convert size to bytes in little endian
  	python3 -c "f = open(\"${tempfile}\",'wb'); f.write(int(${size}).to_bytes(8,'little')); f.close()"
  	# write to header at position 0x8
-@@ -206,13 +206,6 @@ if [ -n "${encryptkey}" ]; then
+@@ -215,13 +215,6 @@ if [ -n "${encryptkey}" ]; then
  	fi;
  fi
  
@@ -50,7 +50,7 @@ Index: Linux_for_Tegra/l4t_sign_image.sh
  set_params_using_chipid
  
  CMD="${L4T_BOOTLOADER_DIR}/tegraflash.py"
-@@ -224,8 +217,9 @@ if [ -n "${ratchet}" ]; then
+@@ -233,8 +226,9 @@ if [ -n "${ratchet}" ]; then
  	options+=("--minratchet_config" "${ratchet}")
  fi
  
@@ -62,9 +62,9 @@ Index: Linux_for_Tegra/l4t_sign_image.sh
  if [ -n "${encryptkey}" ]; then
  	signedfile="$(echo "${output}" | grep "Signed and encrypted file:" | \
  	sed -n "s/.*Signed and encrypted file: //p")"
-@@ -236,10 +230,10 @@ if ! [ -f "${signedfile}" ]; then
- 	echo "${SCRIPT_NAME}: Error: Unable to find the signed file generated by tegraflash.py"
- 	exit 1;
+@@ -245,10 +239,10 @@ if ! [ -f "${signedfile}" ]; then
+ 	echo "${SCRIPT_NAME}: Error: Unable to find the signed file generated by tegraflash.py" >&2
+ 	exit 6;
  fi
 -echo "${SCRIPT_NAME}: Generate header for $(basename "${signedfile}")" >&5
 +[ $quiet -eq 1 ] || echo "${SCRIPT_NAME}: Generate header for $(basename "${signedfile}")"
